/**
 * Curated catalog of default COD form templates seeded on first list.
 *
 * Each template here is a complete `FormSchema` plus catalog metadata. The
 * library is conservative: if a slug already exists in the DB we never
 * overwrite it, so merchants can hand-edit a seeded template without losing
 * their changes on the next deploy.
 */
import type { Prisma } from '@prisma/client';
import type { FormSchema } from '@cashflow-cod/form-schema';
import prisma from '../db.server';

interface DefaultTemplate {
  slug: string;
  name: string;
  category: 'apparel' | 'electronics' | 'food' | 'services' | 'pharmacy' | 'general';
  region?: 'PK' | 'IN' | 'MENA' | 'EU' | 'SEA' | 'GLOBAL';
  language: string;
  description: string;
  isFeatured?: boolean;
  schema: FormSchema;
}

const fNameRequired = {
  id: 'f-name',
  key: 'name',
  type: 'text' as const,
  label: 'Full name',
  placeholder: 'Your full name',
  validation: { required: true, minLength: 2 },
  width: 'full' as const,
};
const fPhoneRequired = {
  id: 'f-phone',
  key: 'phone',
  type: 'phone' as const,
  label: 'Phone number',
  placeholder: '03xx-xxxxxxx',
  validation: { required: true },
  width: 'full' as const,
};
const fAddress = {
  id: 'f-address',
  key: 'address',
  type: 'address' as const,
  label: 'Delivery address',
  placeholder: 'Street, building, area',
  validation: { required: true },
  width: 'full' as const,
};
const fCity = {
  id: 'f-city',
  key: 'city',
  type: 'city' as const,
  label: 'City',
  validation: { required: true },
  width: 'half' as const,
};
const fPostal = {
  id: 'f-postal',
  key: 'postal_code',
  type: 'postal_code' as const,
  label: 'Postal code',
  width: 'half' as const,
};
const fCountry = {
  id: 'f-country',
  key: 'country',
  type: 'country' as const,
  label: 'Country',
  validation: { required: true },
  width: 'full' as const,
};
const fEmail = {
  id: 'f-email',
  key: 'email',
  type: 'email' as const,
  label: 'Email (optional)',
  placeholder: 'you@example.com',
  width: 'full' as const,
};
const fNotes = {
  id: 'f-notes',
  key: 'notes',
  type: 'textarea' as const,
  label: 'Order notes (optional)',
  width: 'full' as const,
};

const fState = {
  id: 'f-state',
  key: 'state',
  type: 'text' as const,
  label: 'State / Province',
  validation: { required: true },
  width: 'half' as const,
};
const fLandmark = {
  id: 'f-landmark',
  key: 'landmark',
  type: 'text' as const,
  label: 'Nearest landmark',
  width: 'full' as const,
};
const fWhatsApp = {
  id: 'f-whatsapp',
  key: 'whatsapp',
  type: 'phone' as const,
  label: 'WhatsApp number',
  placeholder: 'WhatsApp number for order updates',
  width: 'full' as const,
};
const fSize = {
  id: 'f-size',
  key: 'size',
  type: 'select' as const,
  label: 'Size',
  options: [
    { value: 'XS', label: 'XS' },
    { value: 'S', label: 'S' },
    { value: 'M', label: 'M' },
    { value: 'L', label: 'L' },
    { value: 'XL', label: 'XL' },
    { value: 'XXL', label: 'XXL' },
  ],
  validation: { required: true },
  width: 'half' as const,
};
const fColor = {
  id: 'f-color',
  key: 'color',
  type: 'text' as const,
  label: 'Preferred color',
  width: 'half' as const,
};

const DEFAULTS: DefaultTemplate[] = [
  {
    slug: 'cod-classic-single-step',
    name: 'Classic single-step COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description:
      'A clean, single-step COD form with name, phone, address, city, postal code. Best general-purpose default.',
    isFeatured: true,
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Pay when your order arrives.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Cash on Delivery', '7-day returns', 'Free shipping'],
      legalText: 'By placing this order you agree to our terms.',
      steps: [
        {
          id: 'step-1',
          fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-multi-step-trust',
    name: 'Multi-step with trust badges',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description:
      'Two-step flow: contact info first, address second. Reduces drop-off on long forms.',
    isFeatured: true,
    schema: {
      version: 1,
      title: 'Order on delivery',
      subtitle: 'It only takes 30 seconds.',
      submitLabel: 'Confirm order',
      layout: 'multi_step',
      trustBadges: ['Cash on Delivery', 'Easy returns', 'Verified store'],
      legalText: 'No prepayment required.',
      steps: [
        {
          id: 'step-contact',
          title: 'Contact',
          fields: [fNameRequired, fPhoneRequired, fEmail],
        },
        {
          id: 'step-address',
          title: 'Delivery',
          fields: [fAddress, fCity, fPostal, fNotes],
        },
      ],
    },
  },
  {
    slug: 'cod-quantity-offer',
    name: 'Quantity-offer (1 / 2 / 3 ladder)',
    category: 'apparel',
    region: 'GLOBAL',
    language: 'en',
    description:
      'Single-step COD form with a quantity selector and built-in volume-discount messaging in the legal slot.',
    isFeatured: true,
    schema: {
      version: 1,
      title: 'Buy now — Cash on Delivery',
      subtitle: 'Buy more, save more.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Buy 2 get 10% off', 'Buy 3 get 20% off'],
      legalText: 'Discounts auto-apply at checkout.',
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-quantity',
              key: 'quantity',
              type: 'select',
              label: 'Quantity',
              options: [
                { value: '1', label: '1 piece' },
                { value: '2', label: '2 pieces (-10%)' },
                { value: '3', label: '3 pieces (-20%)' },
              ],
              validation: { required: true },
              width: 'full',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-pakistan-urdu',
    name: 'Pakistan COD (Urdu UI)',
    category: 'general',
    region: 'PK',
    language: 'ur',
    description:
      'Localized for Pakistan: Urdu labels, address-first layout, optional landline field, courier-friendly postal code.',
    isFeatured: true,
    schema: {
      version: 1,
      title: 'کیش آن ڈیلیوری',
      subtitle: 'آرڈر گھر پر آنے پر ادائیگی',
      submitLabel: 'آرڈر پلیس کریں',
      layout: 'single',
      trustBadges: ['7 دن ریٹرن', 'مفت شپنگ'],
      legalText: 'آرڈر کرنے سے آپ ہماری شرائط سے متفق ہیں۔',
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'پورا نام' },
            { ...fPhoneRequired, label: 'موبائل نمبر', placeholder: '03xx xxxxxxx' },
            { ...fAddress, label: 'ڈیلیوری ایڈریس' },
            { ...fCity, label: 'شہر' },
            { ...fPostal, label: 'پوسٹل کوڈ' },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-india-multi-language',
    name: 'India COD (English / Hindi)',
    category: 'general',
    region: 'IN',
    language: 'en',
    description:
      'India-specific defaults: pincode validation, state field, optional landmark line. Works for tier-2/3 audiences.',
    isFeatured: false,
    schema: {
      version: 1,
      title: 'Order with Cash on Delivery',
      subtitle: 'Pay at your doorstep.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['7-day returns', 'Free shipping'],
      legalText: '',
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            {
              id: 'f-landmark',
              key: 'landmark',
              type: 'text',
              label: 'Landmark (optional)',
              width: 'full',
            },
            fCity,
            {
              id: 'f-state',
              key: 'state',
              type: 'select',
              label: 'State',
              options: [
                'Andhra Pradesh',
                'Delhi',
                'Gujarat',
                'Karnataka',
                'Kerala',
                'Maharashtra',
                'Punjab',
                'Tamil Nadu',
                'Telangana',
                'Uttar Pradesh',
                'West Bengal',
              ].map((s) => ({ value: s, label: s })),
              validation: { required: true },
              width: 'half',
            },
            { ...fPostal, label: 'Pincode', validation: { required: true, pattern: '^\\d{6}$' } },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-mena-arabic',
    name: 'MENA COD (Arabic UI)',
    category: 'general',
    region: 'MENA',
    language: 'ar',
    description:
      'Right-to-left Arabic layout for the GCC. Country selector defaults to UAE, Saudi, Egypt, Kuwait.',
    isFeatured: false,
    schema: {
      version: 1,
      title: 'الدفع عند الاستلام',
      subtitle: 'ادفع عند تسليم الطلب.',
      submitLabel: 'تأكيد الطلب',
      layout: 'single',
      trustBadges: ['شحن مجاني', 'إرجاع خلال 7 أيام'],
      legalText: '',
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'الاسم الكامل' },
            { ...fPhoneRequired, label: 'رقم الهاتف' },
            { ...fAddress, label: 'عنوان التوصيل' },
            { ...fCity, label: 'المدينة' },
            {
              ...fCountry,
              label: 'الدولة',
              options: [
                { value: 'AE', label: 'الإمارات' },
                { value: 'SA', label: 'السعودية' },
                { value: 'EG', label: 'مصر' },
                { value: 'KW', label: 'الكويت' },
                { value: 'QA', label: 'قطر' },
                { value: 'BH', label: 'البحرين' },
                { value: 'OM', label: 'عُمان' },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-lead-capture-callback',
    name: 'Lead capture (call-me-back)',
    category: 'services',
    region: 'GLOBAL',
    language: 'en',
    description:
      'Minimal 2-field form for high-ticket items: name + phone. Use when you confirm orders by phone before booking the courier.',
    isFeatured: true,
    schema: {
      version: 1,
      title: "Don't miss out — request a callback",
      subtitle: 'We will confirm details by phone before booking.',
      submitLabel: 'Call me back',
      layout: 'single',
      trustBadges: ['Free callback', 'No prepayment'],
      legalText: '',
      steps: [
        {
          id: 'step-1',
          fields: [fNameRequired, fPhoneRequired, fNotes],
        },
      ],
    },
  },
  {
    slug: 'cod-pharmacy-prescription',
    name: 'Pharmacy COD (with prescription)',
    category: 'pharmacy',
    region: 'GLOBAL',
    language: 'en',
    description: 'COD form with prescription-required toggle and pharmacist verification note.',
    isFeatured: false,
    schema: {
      version: 1,
      title: 'Order medicine — Cash on Delivery',
      subtitle: 'A pharmacist will verify your prescription before dispatch.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Verified pharmacist', 'Discreet packaging'],
      legalText: 'Prescription medicines require valid documentation.',
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
            {
              id: 'f-rx',
              key: 'has_prescription',
              type: 'checkbox',
              label: 'I have a valid prescription for this order',
              width: 'full',
            },
            {
              id: 'f-rx-notes',
              key: 'rx_notes',
              type: 'textarea',
              label: 'Prescription notes / pharmacist instructions',
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-electronics-warranty',
    name: 'Electronics COD with warranty opt-in',
    category: 'electronics',
    region: 'GLOBAL',
    language: 'en',
    description:
      'COD with extended-warranty opt-in upsell field. Pair with a quantity-offer for accessories.',
    isFeatured: false,
    schema: {
      version: 1,
      title: 'Buy on COD',
      subtitle: 'With optional extended warranty.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Brand-new sealed', '7-day return'],
      legalText: '',
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
            {
              id: 'f-warranty',
              key: 'extended_warranty',
              type: 'checkbox',
              label: 'Add 1-year extended warranty (+$19)',
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-food-delivery',
    name: 'Food / restaurant COD',
    category: 'food',
    region: 'GLOBAL',
    language: 'en',
    description:
      'Optimized for food delivery: phone first, address with landmark, scheduled-delivery slot.',
    isFeatured: false,
    schema: {
      version: 1,
      title: 'Order food — pay on delivery',
      subtitle: 'Hot food, no card needed.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Hot & fresh', 'Pay cash'],
      legalText: '',
      steps: [
        {
          id: 'step-1',
          fields: [
            fPhoneRequired,
            fNameRequired,
            fAddress,
            {
              id: 'f-landmark',
              key: 'landmark',
              type: 'text',
              label: 'Nearest landmark',
              width: 'full',
            },
            {
              id: 'f-slot',
              key: 'delivery_slot',
              type: 'select',
              label: 'Delivery slot',
              options: [
                { value: 'asap', label: 'As soon as possible' },
                { value: '12_14', label: '12:00 – 14:00' },
                { value: '14_16', label: '14:00 – 16:00' },
                { value: '18_20', label: '18:00 – 20:00' },
                { value: '20_22', label: '20:00 – 22:00' },
              ],
              validation: { required: true },
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  // ───────────────────────────────── Apparel ─────────────────────────────────
  {
    slug: 'cod-apparel-size-color',
    name: 'Apparel with size & color',
    category: 'apparel',
    region: 'GLOBAL',
    language: 'en',
    description: 'Single-step form with size and color pickers for clothing stores.',
    schema: {
      version: 1,
      title: 'Order now — Cash on Delivery',
      subtitle: 'Select your size and we will ship it.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Free exchange', 'Easy returns'],
      steps: [
        {
          id: 'step-1',
          fields: [fSize, fColor, fNameRequired, fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-apparel-multi-step-fit',
    name: 'Apparel multi-step (fit guide)',
    category: 'apparel',
    region: 'GLOBAL',
    language: 'en',
    description: 'Two-step: product options first, delivery second. Includes fit guide note.',
    schema: {
      version: 1,
      title: 'Buy now — pay on delivery',
      subtitle: 'Not sure about size? Easy 7-day exchange.',
      submitLabel: 'Confirm order',
      layout: 'multi_step',
      trustBadges: ['Size exchange', '7-day returns', 'COD available'],
      steps: [
        {
          id: 'step-product',
          title: 'Product',
          fields: [
            fSize,
            fColor,
            {
              id: 'f-qty',
              key: 'quantity',
              type: 'select',
              label: 'Quantity',
              options: [
                { value: '1', label: '1' },
                { value: '2', label: '2' },
                { value: '3', label: '3' },
              ],
              validation: { required: true },
              width: 'half',
            },
          ],
        },
        {
          id: 'step-delivery',
          title: 'Delivery',
          fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-apparel-pk-urdu',
    name: 'Pakistan clothing (Urdu)',
    category: 'apparel',
    region: 'PK',
    language: 'ur',
    description: 'Urdu-labeled apparel form with size picker for Pakistani stores.',
    schema: {
      version: 1,
      title: 'ابھی آرڈر کریں',
      subtitle: 'سائز چنیں — ڈیلیوری پر ادائیگی',
      submitLabel: 'آرڈر کریں',
      layout: 'single',
      trustBadges: ['7 دن ایکسچینج', 'مفت شپنگ'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fSize, label: 'سائز' },
            { ...fColor, label: 'رنگ' },
            { ...fNameRequired, label: 'پورا نام' },
            { ...fPhoneRequired, label: 'فون نمبر', placeholder: '03xx xxxxxxx' },
            { ...fAddress, label: 'ڈیلیوری ایڈریس' },
            { ...fCity, label: 'شہر' },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-apparel-shoes',
    name: 'Shoes & footwear COD',
    category: 'apparel',
    region: 'GLOBAL',
    language: 'en',
    description: 'Shoe-specific form with EU/US size selector.',
    schema: {
      version: 1,
      title: 'Order shoes — Cash on Delivery',
      subtitle: "Free size exchange if they don't fit.",
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Try at home', 'Free exchange'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-shoe-size',
              key: 'shoe_size',
              type: 'select',
              label: 'Shoe size',
              options: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46'].map(
                (s) => ({ value: s, label: `EU ${s}` }),
              ),
              validation: { required: true },
              width: 'half',
            },
            fColor,
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-apparel-bundle-deal',
    name: 'Bundle deal (buy 2 save more)',
    category: 'apparel',
    region: 'GLOBAL',
    language: 'en',
    description: 'Quantity ladder with discount tiers for bundle promotions.',
    schema: {
      version: 1,
      title: 'Bundle & Save — COD',
      subtitle: 'Buy more, pay less per item.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Buy 2 save 15%', 'Buy 3 save 25%', 'Free shipping'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-bundle',
              key: 'quantity',
              type: 'select',
              label: 'Bundle',
              options: [
                { value: '1', label: '1 piece' },
                { value: '2', label: '2 pieces (save 15%)' },
                { value: '3', label: '3 pieces (save 25%)' },
              ],
              validation: { required: true },
              width: 'full',
            },
            fSize,
            fColor,
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Electronics ─────────────────────────────
  {
    slug: 'cod-electronics-mobile',
    name: 'Mobile phones COD',
    category: 'electronics',
    region: 'GLOBAL',
    language: 'en',
    description: 'Phone order form with storage and color variant pickers.',
    schema: {
      version: 1,
      title: 'Order your phone — Cash on Delivery',
      subtitle: 'Brand new, sealed box, pay at your door.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Sealed box', 'Official warranty', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-storage',
              key: 'storage',
              type: 'select',
              label: 'Storage',
              options: [
                { value: '64GB', label: '64 GB' },
                { value: '128GB', label: '128 GB' },
                { value: '256GB', label: '256 GB' },
                { value: '512GB', label: '512 GB' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fColor,
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-electronics-laptop',
    name: 'Laptops & computers COD',
    category: 'electronics',
    region: 'GLOBAL',
    language: 'en',
    description: 'Multi-step form with specs selection and extended warranty option.',
    schema: {
      version: 1,
      title: 'Buy your laptop — pay on delivery',
      subtitle: 'Inspect before you pay.',
      submitLabel: 'Confirm order',
      layout: 'multi_step',
      trustBadges: ['Open & inspect', '1-year warranty', 'Genuine product'],
      steps: [
        {
          id: 'step-config',
          title: 'Configuration',
          fields: [
            {
              id: 'f-ram',
              key: 'ram',
              type: 'select',
              label: 'RAM',
              options: [
                { value: '8GB', label: '8 GB' },
                { value: '16GB', label: '16 GB' },
                { value: '32GB', label: '32 GB' },
              ],
              validation: { required: true },
              width: 'half',
            },
            {
              id: 'f-ssd',
              key: 'storage',
              type: 'select',
              label: 'Storage',
              options: [
                { value: '256GB', label: '256 GB SSD' },
                { value: '512GB', label: '512 GB SSD' },
                { value: '1TB', label: '1 TB SSD' },
              ],
              validation: { required: true },
              width: 'half',
            },
            {
              id: 'f-ext-warranty',
              key: 'extended_warranty',
              type: 'checkbox',
              label: 'Add 2-year extended warranty',
              width: 'full',
            },
          ],
        },
        {
          id: 'step-delivery',
          title: 'Delivery',
          fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-electronics-accessories',
    name: 'Tech accessories COD',
    category: 'electronics',
    region: 'GLOBAL',
    language: 'en',
    description: 'Quick single-step for earbuds, chargers, cables, cases.',
    schema: {
      version: 1,
      title: 'Get it delivered — COD',
      subtitle: 'Accessories shipped fast.',
      submitLabel: 'Order now',
      layout: 'single',
      trustBadges: ['Same-day dispatch', 'Cash on Delivery'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-qty',
              key: 'quantity',
              type: 'select',
              label: 'Quantity',
              options: [
                { value: '1', label: '1' },
                { value: '2', label: '2' },
                { value: '3', label: '3' },
                { value: '5', label: '5' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-electronics-pk',
    name: 'Pakistan electronics (Urdu)',
    category: 'electronics',
    region: 'PK',
    language: 'ur',
    description: 'Electronics COD form in Urdu for Pakistani market.',
    schema: {
      version: 1,
      title: 'کیش آن ڈیلیوری — الیکٹرانکس',
      subtitle: 'اصل پروڈکٹ، وارنٹی کے ساتھ',
      submitLabel: 'آرڈر کریں',
      layout: 'single',
      trustBadges: ['اصل وارنٹی', 'سیلڈ باکس'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'پورا نام' },
            { ...fPhoneRequired, label: 'فون نمبر' },
            { ...fAddress, label: 'ایڈریس' },
            { ...fCity, label: 'شہر' },
            { ...fPostal, label: 'پوسٹل کوڈ' },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Beauty & cosmetics ───────────────────────
  {
    slug: 'cod-beauty-skincare',
    name: 'Skincare COD',
    category: 'beauty',
    region: 'GLOBAL',
    language: 'en',
    description: 'Beauty form with skin type selector for skincare products.',
    schema: {
      version: 1,
      title: 'Order skincare — Cash on Delivery',
      subtitle: 'Dermatologist-tested. Pay when it arrives.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Cruelty-free', 'Dermatologist tested', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-skin',
              key: 'skin_type',
              type: 'select',
              label: 'Skin type',
              options: [
                { value: 'oily', label: 'Oily' },
                { value: 'dry', label: 'Dry' },
                { value: 'combination', label: 'Combination' },
                { value: 'sensitive', label: 'Sensitive' },
                { value: 'normal', label: 'Normal' },
              ],
              width: 'full',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-beauty-makeup',
    name: 'Makeup COD',
    category: 'beauty',
    region: 'GLOBAL',
    language: 'en',
    description: 'Makeup order form with shade selector.',
    schema: {
      version: 1,
      title: 'Get your look — Cash on Delivery',
      subtitle: '100% authentic products.',
      submitLabel: 'Order now',
      layout: 'single',
      trustBadges: ['100% authentic', 'Easy returns'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-shade',
              key: 'shade',
              type: 'text',
              label: 'Shade / color preference',
              width: 'full',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-beauty-perfume',
    name: 'Perfume COD',
    category: 'beauty',
    region: 'GLOBAL',
    language: 'en',
    description: 'Fragrance order form with size option.',
    schema: {
      version: 1,
      title: 'Order fragrance — Cash on Delivery',
      subtitle: 'Original sealed perfumes.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['100% original', 'Sealed box'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-bottle',
              key: 'bottle_size',
              type: 'select',
              label: 'Bottle size',
              options: [
                { value: '30ml', label: '30 ml' },
                { value: '50ml', label: '50 ml' },
                { value: '100ml', label: '100 ml' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-beauty-pk',
    name: 'Pakistan beauty (Urdu)',
    category: 'beauty',
    region: 'PK',
    language: 'ur',
    description: 'Urdu beauty/cosmetics COD form for Pakistan.',
    schema: {
      version: 1,
      title: 'بیوٹی پروڈکٹ آرڈر کریں',
      subtitle: 'اصل پروڈکٹ — ڈیلیوری پر ادائیگی',
      submitLabel: 'آرڈر کریں',
      layout: 'single',
      trustBadges: ['اصل پروڈکٹ', 'آسان واپسی'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'نام' },
            { ...fPhoneRequired, label: 'فون نمبر' },
            { ...fAddress, label: 'ایڈریس' },
            { ...fCity, label: 'شہر' },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Food & grocery ──────────────────────────
  {
    slug: 'cod-food-grocery',
    name: 'Grocery store COD',
    category: 'food',
    region: 'GLOBAL',
    language: 'en',
    description: 'Grocery delivery form with delivery time slot and special instructions.',
    schema: {
      version: 1,
      title: 'Grocery delivery — Cash on Delivery',
      subtitle: 'Fresh groceries at your doorstep.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Fresh guarantee', 'Same-day delivery'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fLandmark,
            {
              id: 'f-slot',
              key: 'delivery_slot',
              type: 'select',
              label: 'Delivery time',
              options: [
                { value: 'morning', label: 'Morning (8 AM – 12 PM)' },
                { value: 'afternoon', label: 'Afternoon (12 PM – 4 PM)' },
                { value: 'evening', label: 'Evening (4 PM – 8 PM)' },
              ],
              validation: { required: true },
              width: 'full',
            },
            { ...fNotes, label: 'Special instructions (allergies, substitutions)' },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-food-bakery',
    name: 'Bakery & sweets COD',
    category: 'food',
    region: 'GLOBAL',
    language: 'en',
    description: 'Bakery order form with custom message and delivery date.',
    schema: {
      version: 1,
      title: 'Order fresh — pay on delivery',
      subtitle: 'Baked fresh for your order.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Freshly baked', 'Same-day delivery'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            {
              id: 'f-msg',
              key: 'cake_message',
              type: 'text',
              label: 'Message on cake (optional)',
              placeholder: 'Happy Birthday!',
              width: 'full',
            },
            fAddress,
            fCity,
            {
              id: 'f-date',
              key: 'delivery_date',
              type: 'text',
              label: 'Delivery date',
              placeholder: 'DD/MM/YYYY',
              validation: { required: true },
              width: 'half',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-food-pk-urdu',
    name: 'Food delivery Pakistan (Urdu)',
    category: 'food',
    region: 'PK',
    language: 'ur',
    description: 'Urdu food delivery form with landmark and delivery slot.',
    schema: {
      version: 1,
      title: 'کھانا آرڈر کریں — ادائیگی ڈیلیوری پر',
      subtitle: 'تازہ اور گرم کھانا',
      submitLabel: 'آرڈر کریں',
      layout: 'single',
      trustBadges: ['تازہ کھانا', 'تیز ڈیلیوری'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fPhoneRequired, label: 'فون نمبر' },
            { ...fNameRequired, label: 'نام' },
            { ...fAddress, label: 'ایڈریس' },
            { ...fLandmark, label: 'قریبی نشانی' },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Services ────────────────────────────────
  {
    slug: 'cod-services-booking',
    name: 'Service booking COD',
    category: 'services',
    region: 'GLOBAL',
    language: 'en',
    description: 'Book a service and pay on completion. Includes date/time selection.',
    schema: {
      version: 1,
      title: 'Book a service — pay on completion',
      subtitle: 'We come to you.',
      submitLabel: 'Book now',
      layout: 'single',
      trustBadges: ['Pay after service', 'Verified professionals'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            {
              id: 'f-service-date',
              key: 'service_date',
              type: 'text',
              label: 'Preferred date',
              placeholder: 'DD/MM/YYYY',
              validation: { required: true },
              width: 'half',
            },
            {
              id: 'f-service-time',
              key: 'service_time',
              type: 'select',
              label: 'Preferred time',
              options: [
                { value: 'morning', label: 'Morning' },
                { value: 'afternoon', label: 'Afternoon' },
                { value: 'evening', label: 'Evening' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fAddress,
            fCity,
            fNotes,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-services-consultation',
    name: 'Consultation request',
    category: 'services',
    region: 'GLOBAL',
    language: 'en',
    description: 'Request a consultation call. Minimal form with availability preferences.',
    schema: {
      version: 1,
      title: 'Request a consultation',
      subtitle: 'Free consultation — no commitment.',
      submitLabel: 'Request callback',
      layout: 'single',
      trustBadges: ['Free consultation', 'No obligation'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fEmail,
            {
              id: 'f-avail',
              key: 'availability',
              type: 'select',
              label: 'Best time to call',
              options: [
                { value: 'morning', label: 'Morning (9 AM – 12 PM)' },
                { value: 'afternoon', label: 'Afternoon (12 PM – 5 PM)' },
                { value: 'evening', label: 'Evening (5 PM – 8 PM)' },
              ],
              width: 'full',
            },
            fNotes,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-services-home-repair',
    name: 'Home repair / handyman',
    category: 'services',
    region: 'GLOBAL',
    language: 'en',
    description: 'Home repair service form with issue description and photo upload note.',
    schema: {
      version: 1,
      title: 'Book a repair — pay after service',
      subtitle: 'Certified technicians at your door.',
      submitLabel: 'Book service',
      layout: 'single',
      trustBadges: ['Pay after service', 'Certified technician'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            {
              id: 'f-issue',
              key: 'issue_description',
              type: 'textarea',
              label: 'Describe the issue',
              placeholder: 'E.g. Leaking faucet in kitchen',
              validation: { required: true },
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Pharmacy ────────────────────────────────
  {
    slug: 'cod-pharmacy-otc',
    name: 'OTC medicine COD',
    category: 'pharmacy',
    region: 'GLOBAL',
    language: 'en',
    description: 'Over-the-counter medicine delivery. No prescription needed.',
    schema: {
      version: 1,
      title: 'Order medicine — Cash on Delivery',
      subtitle: 'No prescription required for OTC products.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Licensed pharmacy', 'Genuine medicine'],
      steps: [
        { id: 'step-1', fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal, fNotes] },
      ],
    },
  },
  {
    slug: 'cod-pharmacy-pk',
    name: 'Pakistan pharmacy (Urdu)',
    category: 'pharmacy',
    region: 'PK',
    language: 'ur',
    description: 'Urdu pharmacy COD form for Pakistani medical stores.',
    schema: {
      version: 1,
      title: 'دوائی آرڈر کریں — ادائیگی ڈیلیوری پر',
      subtitle: 'لائسنس یافتہ فارمیسی',
      submitLabel: 'آرڈر کریں',
      layout: 'single',
      trustBadges: ['اصل دوائی', 'لائسنس یافتہ'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'مریض کا نام' },
            { ...fPhoneRequired, label: 'فون نمبر' },
            { ...fAddress, label: 'ایڈریس' },
            { ...fCity, label: 'شہر' },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Regional (PK) ──────────────────────────
  {
    slug: 'cod-pk-whatsapp',
    name: 'Pakistan WhatsApp COD',
    category: 'general',
    region: 'PK',
    language: 'en',
    description: 'COD form with WhatsApp number field for order tracking in Pakistan.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Order via WhatsApp — pay at your door.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['WhatsApp updates', 'Free shipping', 'COD'],
      steps: [
        {
          id: 'step-1',
          fields: [fNameRequired, fPhoneRequired, fWhatsApp, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-pk-multi-step',
    name: 'Pakistan multi-step COD',
    category: 'general',
    region: 'PK',
    language: 'en',
    description: 'Multi-step COD form optimized for Pakistan with city and area fields.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Fill in your details in 2 easy steps.',
      submitLabel: 'Place order',
      layout: 'multi_step',
      trustBadges: ['Free shipping', '7-day returns'],
      steps: [
        { id: 'step-contact', title: 'Contact', fields: [fNameRequired, fPhoneRequired, fEmail] },
        { id: 'step-address', title: 'Address', fields: [fAddress, fLandmark, fCity, fPostal] },
      ],
    },
  },
  {
    slug: 'cod-pk-lahore-karachi',
    name: 'Pakistan city-specific COD',
    category: 'general',
    region: 'PK',
    language: 'en',
    description: 'City selector with major Pakistani cities for faster routing.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Free delivery in major cities.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Free delivery', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            {
              id: 'f-pk-city',
              key: 'city',
              type: 'select',
              label: 'City',
              options: [
                'Karachi',
                'Lahore',
                'Islamabad',
                'Rawalpindi',
                'Faisalabad',
                'Multan',
                'Peshawar',
                'Quetta',
                'Sialkot',
                'Gujranwala',
                'Hyderabad',
                'Bahawalpur',
              ].map((c) => ({ value: c, label: c })),
              validation: { required: true },
              width: 'half',
            },
            fPostal,
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Regional (India) ────────────────────────
  {
    slug: 'cod-india-pincode',
    name: 'India COD with pincode',
    category: 'general',
    region: 'IN',
    language: 'en',
    description: 'India-focused form with pincode validation and state selector.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Pay when your order arrives.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['7-day returns', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fLandmark,
            {
              id: 'f-in-state',
              key: 'state',
              type: 'select',
              label: 'State',
              options: [
                'Andhra Pradesh',
                'Assam',
                'Bihar',
                'Delhi',
                'Goa',
                'Gujarat',
                'Haryana',
                'Himachal Pradesh',
                'Jharkhand',
                'Karnataka',
                'Kerala',
                'Madhya Pradesh',
                'Maharashtra',
                'Odisha',
                'Punjab',
                'Rajasthan',
                'Tamil Nadu',
                'Telangana',
                'Uttar Pradesh',
                'West Bengal',
              ].map((s) => ({ value: s, label: s })),
              validation: { required: true },
              width: 'half',
            },
            { ...fPostal, label: 'Pincode', validation: { required: true, pattern: '^\\d{6}$' } },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-india-hindi',
    name: 'India COD (Hindi)',
    category: 'general',
    region: 'IN',
    language: 'hi',
    description: 'Hindi-language COD form for Indian market.',
    schema: {
      version: 1,
      title: 'कैश ऑन डिलीवरी',
      subtitle: 'ऑर्डर आने पर भुगतान करें।',
      submitLabel: 'ऑर्डर दें',
      layout: 'single',
      trustBadges: ['7 दिन रिटर्न', 'मुफ्त शिपिंग'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'पूरा नाम' },
            { ...fPhoneRequired, label: 'फोन नंबर' },
            { ...fAddress, label: 'डिलीवरी पता' },
            { ...fCity, label: 'शहर' },
            { ...fPostal, label: 'पिनकोड' },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-india-multi-step',
    name: 'India multi-step COD',
    category: 'general',
    region: 'IN',
    language: 'en',
    description: 'Two-step COD form for India with landmark and alternate phone.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Quick 2-step checkout.',
      submitLabel: 'Confirm order',
      layout: 'multi_step',
      trustBadges: ['Free delivery', 'Easy returns'],
      steps: [
        {
          id: 'step-contact',
          title: 'Contact',
          fields: [
            fNameRequired,
            fPhoneRequired,
            {
              id: 'f-alt-phone',
              key: 'alt_phone',
              type: 'phone',
              label: 'Alternate phone (optional)',
              width: 'full',
            },
          ],
        },
        {
          id: 'step-address',
          title: 'Address',
          fields: [
            fAddress,
            fLandmark,
            fCity,
            { ...fPostal, label: 'Pincode', validation: { required: true } },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Regional (MENA / Arabic) ────────────────
  {
    slug: 'cod-mena-multi-step',
    name: 'MENA multi-step (Arabic)',
    category: 'general',
    region: 'MENA',
    language: 'ar',
    description: 'Arabic two-step form for Gulf countries with country selector.',
    schema: {
      version: 1,
      title: 'الدفع عند الاستلام',
      subtitle: 'خطوتان بسيطتان لإتمام الطلب',
      submitLabel: 'تأكيد الطلب',
      layout: 'multi_step',
      trustBadges: ['شحن مجاني', 'إرجاع سهل'],
      steps: [
        {
          id: 'step-contact',
          title: 'بيانات التواصل',
          fields: [
            { ...fNameRequired, label: 'الاسم الكامل' },
            { ...fPhoneRequired, label: 'رقم الهاتف' },
            { ...fWhatsApp, label: 'واتساب' },
          ],
        },
        {
          id: 'step-address',
          title: 'عنوان التوصيل',
          fields: [
            { ...fAddress, label: 'العنوان' },
            { ...fCity, label: 'المدينة' },
            {
              id: 'f-mena-country',
              key: 'country',
              type: 'select',
              label: 'الدولة',
              options: [
                { value: 'AE', label: 'الإمارات' },
                { value: 'SA', label: 'السعودية' },
                { value: 'EG', label: 'مصر' },
                { value: 'KW', label: 'الكويت' },
                { value: 'QA', label: 'قطر' },
                { value: 'BH', label: 'البحرين' },
                { value: 'OM', label: 'عُمان' },
                { value: 'JO', label: 'الأردن' },
                { value: 'IQ', label: 'العراق' },
              ],
              validation: { required: true },
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-saudi-arabia',
    name: 'Saudi Arabia COD',
    category: 'general',
    region: 'MENA',
    language: 'ar',
    description: 'Saudi-specific COD form with Saudi city selector.',
    schema: {
      version: 1,
      title: 'الدفع عند الاستلام',
      subtitle: 'توصيل سريع في المملكة',
      submitLabel: 'اطلب الآن',
      layout: 'single',
      trustBadges: ['توصيل سريع', 'دفع عند الاستلام'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'الاسم' },
            { ...fPhoneRequired, label: 'رقم الجوال' },
            { ...fAddress, label: 'العنوان' },
            {
              id: 'f-sa-city',
              key: 'city',
              type: 'select',
              label: 'المدينة',
              options: [
                'الرياض',
                'جدة',
                'مكة',
                'المدينة',
                'الدمام',
                'الخبر',
                'تبوك',
                'أبها',
                'الطائف',
                'نجران',
                'جيزان',
                'حائل',
              ].map((c) => ({ value: c, label: c })),
              validation: { required: true },
              width: 'half',
            },
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-uae-emirates',
    name: 'UAE COD',
    category: 'general',
    region: 'MENA',
    language: 'ar',
    description: 'UAE-specific form with emirate selector.',
    schema: {
      version: 1,
      title: 'اطلب الآن — الدفع عند التوصيل',
      subtitle: 'توصيل في جميع الإمارات',
      submitLabel: 'تأكيد الطلب',
      layout: 'single',
      trustBadges: ['توصيل مجاني', 'دفع نقدي'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'الاسم' },
            { ...fPhoneRequired, label: 'رقم الهاتف' },
            { ...fAddress, label: 'العنوان' },
            {
              id: 'f-emirate',
              key: 'emirate',
              type: 'select',
              label: 'الإمارة',
              options: [
                'أبوظبي',
                'دبي',
                'الشارقة',
                'عجمان',
                'أم القيوين',
                'رأس الخيمة',
                'الفجيرة',
              ].map((c) => ({ value: c, label: c })),
              validation: { required: true },
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Regional (SEA) ──────────────────────────
  {
    slug: 'cod-sea-english',
    name: 'Southeast Asia COD',
    category: 'general',
    region: 'SEA',
    language: 'en',
    description: 'English COD form for Malaysia, Philippines, Indonesia, Thailand.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Pay when your parcel arrives.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['COD available', 'Free shipping'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            {
              id: 'f-sea-country',
              key: 'country',
              type: 'select',
              label: 'Country',
              options: [
                { value: 'MY', label: 'Malaysia' },
                { value: 'PH', label: 'Philippines' },
                { value: 'ID', label: 'Indonesia' },
                { value: 'TH', label: 'Thailand' },
                { value: 'VN', label: 'Vietnam' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-philippines',
    name: 'Philippines COD',
    category: 'general',
    region: 'SEA',
    language: 'en',
    description: 'Philippines COD with barangay and province fields.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Pay when your order arrives.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['COD nationwide', 'Free shipping over ₱999'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fAddress,
            {
              id: 'f-brgy',
              key: 'barangay',
              type: 'text',
              label: 'Barangay',
              validation: { required: true },
              width: 'half',
            },
            fCity,
            {
              id: 'f-province',
              key: 'province',
              type: 'text',
              label: 'Province',
              validation: { required: true },
              width: 'half',
            },
            fPostal,
          ],
        },
      ],
    },
  },
  // ──────────────────────────────── Regional (EU / Europe) ──────────────────
  {
    slug: 'cod-europe-english',
    name: 'Europe COD (English)',
    category: 'general',
    region: 'EU',
    language: 'en',
    description: 'European COD with country selector for EU shipping.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Pay when you receive your order.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['14-day returns', 'EU shipping'],
      steps: [
        {
          id: 'step-1',
          fields: [
            fNameRequired,
            fPhoneRequired,
            fEmail,
            fAddress,
            fCity,
            {
              id: 'f-eu-country',
              key: 'country',
              type: 'select',
              label: 'Country',
              options: [
                { value: 'DE', label: 'Germany' },
                { value: 'AT', label: 'Austria' },
                { value: 'RO', label: 'Romania' },
                { value: 'BG', label: 'Bulgaria' },
                { value: 'CZ', label: 'Czech Republic' },
                { value: 'PL', label: 'Poland' },
                { value: 'HU', label: 'Hungary' },
                { value: 'GR', label: 'Greece' },
                { value: 'IT', label: 'Italy' },
                { value: 'ES', label: 'Spain' },
                { value: 'HR', label: 'Croatia' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-turkey',
    name: 'Turkey COD (Kapıda Ödeme)',
    category: 'general',
    region: 'EU',
    language: 'tr',
    description: 'Turkish-language COD form.',
    schema: {
      version: 1,
      title: 'Kapıda Ödeme',
      subtitle: 'Siparişiniz geldiğinde ödeyin.',
      submitLabel: 'Sipariş ver',
      layout: 'single',
      trustBadges: ['Ücretsiz kargo', 'Kolay iade'],
      steps: [
        {
          id: 'step-1',
          fields: [
            { ...fNameRequired, label: 'Ad Soyad' },
            { ...fPhoneRequired, label: 'Telefon' },
            { ...fAddress, label: 'Adres' },
            { ...fCity, label: 'İl / İlçe' },
            { ...fPostal, label: 'Posta kodu' },
          ],
        },
      ],
    },
  },
  // ─────────────────── General / multi-purpose ──────────────────────────────
  {
    slug: 'cod-minimal-2-field',
    name: 'Minimal 2-field (name + phone)',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Ultra-minimal COD form — just name and phone. Great for WhatsApp-first stores.',
    schema: {
      version: 1,
      title: 'Order now',
      subtitle: 'We will call to confirm your order.',
      submitLabel: 'Submit',
      layout: 'single',
      trustBadges: ['Quick order', 'Phone confirmation'],
      steps: [{ id: 'step-1', fields: [fNameRequired, fPhoneRequired] }],
    },
  },
  {
    slug: 'cod-with-email',
    name: 'COD with email capture',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Standard COD form that also captures email for marketing.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Fill in your details.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Free shipping', 'Easy returns'],
      steps: [
        { id: 'step-1', fields: [fNameRequired, fEmail, fPhoneRequired, fAddress, fCity, fPostal] },
      ],
    },
  },
  {
    slug: 'cod-with-discount-code',
    name: 'COD with discount code',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'COD form with a discount code input. Pair with shop discount rules.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Have a discount code? Enter it below.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Discounts accepted', 'Free shipping'],
      allowDiscountCode: true,
      steps: [{ id: 'step-1', fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal] }],
    },
  },
  {
    slug: 'cod-3-step-wizard',
    name: '3-step wizard',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Three-step checkout wizard: Contact → Address → Review. Reduces form fatigue.',
    schema: {
      version: 1,
      title: 'Cash on Delivery',
      subtitle: 'Just 3 quick steps.',
      submitLabel: 'Confirm order',
      layout: 'multi_step',
      trustBadges: ['3 easy steps', 'Secure order'],
      steps: [
        { id: 'step-1', title: 'Contact', fields: [fNameRequired, fPhoneRequired] },
        { id: 'step-2', title: 'Address', fields: [fAddress, fCity, fPostal] },
        { id: 'step-3', title: 'Confirm', fields: [fEmail, fNotes] },
      ],
    },
  },
  {
    slug: 'cod-gift-order',
    name: 'Gift order COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'COD form with gift wrapping option and recipient details.',
    schema: {
      version: 1,
      title: 'Send a gift — Cash on Delivery',
      subtitle: 'We will gift-wrap it for you.',
      submitLabel: 'Place gift order',
      layout: 'multi_step',
      trustBadges: ['Gift wrapping', 'Surprise delivery'],
      steps: [
        { id: 'step-sender', title: 'Your info', fields: [fNameRequired, fPhoneRequired] },
        {
          id: 'step-recipient',
          title: 'Recipient',
          fields: [
            {
              id: 'f-rcpt-name',
              key: 'recipient_name',
              type: 'text',
              label: 'Recipient name',
              validation: { required: true },
              width: 'full',
            },
            {
              id: 'f-rcpt-phone',
              key: 'recipient_phone',
              type: 'phone',
              label: 'Recipient phone',
              validation: { required: true },
              width: 'full',
            },
            fAddress,
            fCity,
            fPostal,
            {
              id: 'f-gift-msg',
              key: 'gift_message',
              type: 'textarea',
              label: 'Gift message (optional)',
              width: 'full',
            },
            {
              id: 'f-gift-wrap',
              key: 'gift_wrap',
              type: 'checkbox',
              label: 'Add gift wrapping',
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-subscription-first-order',
    name: 'Subscription first order COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'First-order COD for subscription products. Captures frequency preference.',
    schema: {
      version: 1,
      title: 'Subscribe — first order COD',
      subtitle: 'Pay cash for your first delivery. Cancel anytime.',
      submitLabel: 'Start subscription',
      layout: 'single',
      trustBadges: ['Cancel anytime', 'First order COD'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-freq',
              key: 'frequency',
              type: 'select',
              label: 'Delivery frequency',
              options: [
                { value: 'weekly', label: 'Every week' },
                { value: 'biweekly', label: 'Every 2 weeks' },
                { value: 'monthly', label: 'Every month' },
              ],
              validation: { required: true },
              width: 'full',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-wholesale-bulk',
    name: 'Wholesale / bulk order COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Bulk order form with company name and large quantity selector.',
    schema: {
      version: 1,
      title: 'Bulk order — Cash on Delivery',
      subtitle: 'Wholesale pricing for large orders.',
      submitLabel: 'Request quote',
      layout: 'single',
      trustBadges: ['Bulk pricing', 'COD for businesses'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-company',
              key: 'company',
              type: 'text',
              label: 'Company name (optional)',
              width: 'full',
            },
            fNameRequired,
            fPhoneRequired,
            fEmail,
            {
              id: 'f-bulk-qty',
              key: 'quantity',
              type: 'select',
              label: 'Quantity',
              options: [
                { value: '10', label: '10 units' },
                { value: '25', label: '25 units' },
                { value: '50', label: '50 units' },
                { value: '100', label: '100 units' },
                { value: '200+', label: '200+ units' },
              ],
              validation: { required: true },
              width: 'half',
            },
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-flash-sale',
    name: 'Flash sale COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Urgency-driven COD form for limited-time offers.',
    schema: {
      version: 1,
      title: 'Flash sale — Order now!',
      subtitle: 'Limited stock — Cash on Delivery.',
      submitLabel: 'Grab it now',
      layout: 'single',
      trustBadges: ['Limited stock', 'Fast dispatch', 'COD available'],
      steps: [{ id: 'step-1', fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal] }],
    },
  },
  {
    slug: 'cod-preorder',
    name: 'Pre-order COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Pre-order form for upcoming product launches. Pay on delivery.',
    schema: {
      version: 1,
      title: 'Pre-order — Cash on Delivery',
      subtitle: 'Be first to get it. Pay when it ships.',
      submitLabel: 'Reserve my order',
      layout: 'single',
      trustBadges: ['Pre-order guarantee', 'Pay on delivery'],
      steps: [
        { id: 'step-1', fields: [fNameRequired, fPhoneRequired, fEmail, fAddress, fCity, fPostal] },
      ],
    },
  },
  {
    slug: 'cod-digital-physical-hybrid',
    name: 'Digital + physical hybrid',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'For products that include both digital and physical components.',
    schema: {
      version: 1,
      title: 'Order — Cash on Delivery',
      subtitle: 'Digital access instantly, physical item shipped.',
      submitLabel: 'Place order',
      layout: 'multi_step',
      trustBadges: ['Instant digital access', 'COD for physical item'],
      steps: [
        { id: 'step-digital', title: 'Digital access', fields: [fNameRequired, fEmail] },
        {
          id: 'step-physical',
          title: 'Shipping',
          fields: [fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-custom-product',
    name: 'Custom / personalized product',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'For products that need customization details (engraving, printing, etc.).',
    schema: {
      version: 1,
      title: 'Customize & Order — COD',
      subtitle: 'Tell us how you want it.',
      submitLabel: 'Place order',
      layout: 'multi_step',
      trustBadges: ['Custom made', 'Pay on delivery'],
      steps: [
        {
          id: 'step-custom',
          title: 'Customize',
          fields: [
            {
              id: 'f-custom-text',
              key: 'custom_text',
              type: 'text',
              label: 'Custom text / name to print',
              placeholder: 'E.g. Happy Birthday Ali',
              width: 'full',
            },
            fColor,
            { ...fNotes, label: 'Special instructions' },
          ],
        },
        {
          id: 'step-delivery',
          title: 'Delivery',
          fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal],
        },
      ],
    },
  },
  {
    slug: 'cod-kids-toys',
    name: 'Kids & toys COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Toy store COD form with age group selector.',
    schema: {
      version: 1,
      title: 'Order toys — Cash on Delivery',
      subtitle: 'Make them smile.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Safe & certified', 'Gift-ready'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-age',
              key: 'age_group',
              type: 'select',
              label: 'Age group',
              options: [
                { value: '0-2', label: '0–2 years' },
                { value: '3-5', label: '3–5 years' },
                { value: '6-9', label: '6–9 years' },
                { value: '10-14', label: '10–14 years' },
              ],
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
            {
              id: 'f-gift-wrap-toy',
              key: 'gift_wrap',
              type: 'checkbox',
              label: 'Gift wrap this order',
              width: 'full',
            },
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-pet-supplies',
    name: 'Pet supplies COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Pet store form with pet type selector.',
    schema: {
      version: 1,
      title: 'Pet supplies — Cash on Delivery',
      subtitle: 'Everything for your furry friend.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Vet approved', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-pet',
              key: 'pet_type',
              type: 'select',
              label: 'Pet type',
              options: [
                { value: 'dog', label: 'Dog' },
                { value: 'cat', label: 'Cat' },
                { value: 'bird', label: 'Bird' },
                { value: 'fish', label: 'Fish' },
                { value: 'other', label: 'Other' },
              ],
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-jewelry',
    name: 'Jewelry COD',
    category: 'beauty',
    region: 'GLOBAL',
    language: 'en',
    description: 'Jewelry order form with ring size option.',
    schema: {
      version: 1,
      title: 'Order jewelry — Cash on Delivery',
      subtitle: 'Inspect before you pay.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Inspect on delivery', 'Authenticity certificate'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-ring-size',
              key: 'ring_size',
              type: 'select',
              label: 'Ring size (if applicable)',
              options: [
                { value: 'N/A', label: 'Not a ring' },
                { value: '5', label: 'Size 5' },
                { value: '6', label: 'Size 6' },
                { value: '7', label: 'Size 7' },
                { value: '8', label: 'Size 8' },
                { value: '9', label: 'Size 9' },
                { value: '10', label: 'Size 10' },
              ],
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-fitness-supplements',
    name: 'Fitness & supplements COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Supplements COD form with flavor selector.',
    schema: {
      version: 1,
      title: 'Order supplements — COD',
      subtitle: '100% genuine products.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['100% genuine', 'Lab tested', 'COD available'],
      steps: [
        {
          id: 'step-1',
          fields: [
            {
              id: 'f-flavor',
              key: 'flavor',
              type: 'select',
              label: 'Flavor',
              options: [
                { value: 'chocolate', label: 'Chocolate' },
                { value: 'vanilla', label: 'Vanilla' },
                { value: 'strawberry', label: 'Strawberry' },
                { value: 'unflavored', label: 'Unflavored' },
              ],
              width: 'half',
            },
            fNameRequired,
            fPhoneRequired,
            fAddress,
            fCity,
            fPostal,
          ],
        },
      ],
    },
  },
  {
    slug: 'cod-home-decor',
    name: 'Home decor COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Home decor and furniture COD form.',
    schema: {
      version: 1,
      title: 'Order home decor — Cash on Delivery',
      subtitle: 'Beautiful pieces, pay on arrival.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Inspect on delivery', 'Easy returns'],
      steps: [
        {
          id: 'step-1',
          fields: [fNameRequired, fPhoneRequired, fAddress, fLandmark, fCity, fPostal, fNotes],
        },
      ],
    },
  },
  {
    slug: 'cod-books-stationery',
    name: 'Books & stationery COD',
    category: 'general',
    region: 'GLOBAL',
    language: 'en',
    description: 'Simple COD form for bookstores and stationery shops.',
    schema: {
      version: 1,
      title: 'Order books — Cash on Delivery',
      subtitle: 'Knowledge at your doorstep.',
      submitLabel: 'Place order',
      layout: 'single',
      trustBadges: ['Brand new', 'Fast delivery'],
      steps: [{ id: 'step-1', fields: [fNameRequired, fPhoneRequired, fAddress, fCity, fPostal] }],
    },
  },
];

export async function ensureDefaultTemplatesSeeded(): Promise<number> {
  const existing = await prisma.formTemplate.findMany({
    where: { slug: { in: DEFAULTS.map((d) => d.slug) } },
    select: { slug: true },
  });
  const have = new Set(existing.map((e) => e.slug));
  const missing = DEFAULTS.filter((d) => !have.has(d.slug));
  if (missing.length === 0) return 0;
  await prisma.formTemplate.createMany({
    data: missing.map((m) => ({
      slug: m.slug,
      name: m.name,
      category: m.category,
      region: m.region,
      language: m.language,
      description: m.description,
      schema: m.schema as Prisma.InputJsonValue,
      isFeatured: Boolean(m.isFeatured),
    })),
    skipDuplicates: true,
  });
  return missing.length;
}

export const DEFAULT_TEMPLATE_SLUGS = DEFAULTS.map((d) => d.slug);
